### ISSUE TITLE
could not find any strategy named `rsync_with_remote_cache'

### ISSUE THREAD

**Issue by naillizard** [vigetlabs/capistrano_rsync_with_remote_cache#24]
This works fine

``` sh
cap deploy:setup
```

But when I run

``` sh
cap deploy:check
    triggering load callbacks
  * 2013-06-05 14:21:55 executing `staging'
    triggering start callbacks for `deploy:check'
  * 2013-06-05 14:21:55 executing `multistage:ensure'
  * 2013-06-05 14:21:55 executing `deploy:check'
could not find any strategy named `rsync_with_remote_cache'
```

**Comment by naillizard** [comment]
my default env is staging.rb

``` ruby
  #staging.rb
  1 #set :strategy, Capistrano::Deploy::strategy::RsyncWithRemoteCache
  2 default_run_options[:env] = {'PATH' => '/usr/local/bin:/usr/bin:$PATH'}
  3 server "172.20.60.182", :app, :web, :db, :primary => true
  4 set :application, "test"
  5 set :application_path, "/var/www/html/classic/#{application}"
  6 set :user, "user"
  7 set :password, "password"
  8 set :scm, :git
  9 set :git_shallow_clone, 1
 10 set :scm_verbose, true
 11 ssh_options[:keys] = %w(~/.ssh/id_rsa)
 12 ssh_options[:forward_agent] = true
 13 set :repository, "git@172.20.60.183/current-system.git"
 14 set :branch, "develop"
 15 set :deploy_to, "#{application_path}"
 16 set :deploy_via, :rsync_with_remote_cache
 17 
 18 after :deploy, :migrate
 19 set :mysql_db_name, "dbname"
 20 set :mysql_params, "-u user -pPassword"
 21 desc "Migrate database #{mysql_db_name}"
 22 
 23 task :migrate, :roles => :db do
 24     run "mysql #{mysql_params} #{mysql_db_name} < #{current_path}/sql_changes.sql"
 25 end
```
1. I tried requiring capistrano_rsync_with_remote_cache, but it throws a lot of errors.

``` sh
cap deploy:setup
triggering load callbacks
  * 2013-06-06 08:28:43 executing `staging'
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:45:in `gem_original_require': no such file to load --
capistrano_rsync_with_remote_cache (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:152:in `require'
    from ./config/deploy/staging.rb:1:in `load'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:172:in
`load_from_file'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:89:in `load'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:86:in `load'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:86:in `each'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:86:in `load'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/ext/multistage.rb:18
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in
`instance_eval'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in
`invoke_task_directly_without_callbacks'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:25:in
`invoke_task_directly'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:89:in
`execute_task'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:101:in
`find_and_execute_task'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/ext/multistage.rb:28
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/callback.rb:25:in `call'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/callback.rb:25:in `call'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:33:in `execute!'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Library/Ruby/Gems/1.8/gems/capistrano-2.14.2/bin/cap:4
    from /usr/bin/cap:23:in `load'
    from /usr/bin/cap:23
```

I even tried to copy the rsync_remote_with_cache strategy into my capistrano/..../strategy folder, but that didn't work either, same error even after fixing require path to 'capistrano/recipes/deploy/strategy/rsync_with_remote_cache'
Do I need to uncomment line 1?

**Comment by naillizard** [comment]
Ignore this, my environment was a mess. had ruby193 installed, gem 2.0.3 path was different than what ruby was using, it was still using OS X default Ruby gems path.
